wx:
  url:
    redirect_uri: http://tdgyyx.sunlinka.com/api/auth/token
  public_number:
    app_id: wx01aef8db5f5ffb0f
    app_secret: 4f2add778b4ab69de8e10652daf238de
    config_token: developer_home
service:
  package: org.yyx.wx.serviceimpl