wx:
  url:
    redirect_uri: http%3a%2f%2fyyx.sunlinka.com%2fapi%2fauth%2ftoken
  public_number:
    app_id: wx65bd0a2e9cdf16b6
    app_secret: 6b73bcc96614f9b8eb8899c849974ed2
    config_token: developer_home
spring:
  redis:
    host: 192.168.1.17
    #host: 172.21.0.4
    password: 1q2w3e4r`
    port: 40081
logging:
  level:
    org:
      yyx:
        wx: info