wx:
  url:
    redirect_uri: http%3a%2f%2fyzwtest.6655.la%2fapi%2fauth%2ftoken
  public_number:
    app_id: wx65bd0a2e9cdf16b6
    app_secret: 6b73bcc96614f9b8eb8899c849974ed2
    config_token: developer_home
spring:
  redis:
    host: 10.211.55.5
    password: 1q2w3e4r`