server:
  port: 8080
  servlet:
    context-path: /api/
spring:
  http:
    encoding:
      charset: utf-8
  profiles:
    active: prod
wx:
  url:
    # 获取AccessToken的URL 此AccessToken不能用于获取OPENID
    get_access_token: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=
    # 创建Ticket的URL
    create_ticket: https://api.weixin.qq.com/cgi-bin/qrcode/create?access_token=
    # 通过Ticket换取二维码的URL
    get_qr_code: https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=
